services:
  pdf-extractext:
    image: pdf-extractext:${APP_VERSION:-1.0.0}
    environment:
      - TZ=America/Argentina/Mendoza
    build:
      context: ../
      dockerfile: infra/Dockerfile
    env_file:
      - ../.env
    networks:
      - pdfnet
    labels:
      traefik.enable: "true"
      traefik.http.routers.pdf-extractext.rule: "Host(`pdf-extractext.universidad.localhost`)"
      traefik.http.routers.pdf-extractext.tls: "true"
      traefik.http.services.pdf-extractext.loadbalancer.server.port: "8000"

networks:
  pdfnet:
    external: true
    name: red_compartida_pdf
